import type { BrainSprintLesson } from "@/lib/brain-sprint/types";

export const SAMPLE_LESSONS: BrainSprintLesson[] = [
  {
    id: "math-1",
    track: "math",
    number: 1,
    title: "Addition - Single Digit",
    description: "Type the answer to each addition problem.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "3 + 4 = ?", answer: "7" },
      { id: "q2", question: "5 + 2 = ?", answer: "7" },
      { id: "q3", question: "8 + 1 = ?", answer: "9" },
      { id: "q4", question: "6 + 3 = ?", answer: "9" },
      { id: "q5", question: "4 + 5 = ?", answer: "9" },
      { id: "q6", question: "7 + 2 = ?", answer: "9" },
      { id: "q7", question: "2 + 6 = ?", answer: "8" },
      { id: "q8", question: "9 + 0 = ?", answer: "9" },
      { id: "q9", question: "3 + 5 = ?", answer: "8" },
      { id: "q10", question: "4 + 4 = ?", answer: "8" },
      { id: "q11", question: "6 + 2 = ?", answer: "8" },
      { id: "q12", question: "5 + 5 = ?", answer: "10" },
      { id: "q13", question: "7 + 3 = ?", answer: "10" },
      { id: "q14", question: "8 + 2 = ?", answer: "10" },
      { id: "q15", question: "9 + 1 = ?", answer: "10" },
    ],
  },

  // ─── MATH MASTERY (Lessons 2-10) ───
  {
    id: "math-2",
    track: "math",
    number: 2,
    title: "Addition - Double Digit",
    description: "Add two-digit numbers. Type the sum.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "12 + 15 = ?", answer: "27" },
      { id: "q2", question: "23 + 14 = ?", answer: "37" },
      { id: "q3", question: "31 + 26 = ?", answer: "57" },
      { id: "q4", question: "45 + 22 = ?", answer: "67" },
      { id: "q5", question: "18 + 11 = ?", answer: "29" },
      { id: "q6", question: "24 + 35 = ?", answer: "59" },
      { id: "q7", question: "16 + 27 = ?", answer: "43" },
      { id: "q8", question: "33 + 28 = ?", answer: "61" },
      { id: "q9", question: "47 + 19 = ?", answer: "66" },
      { id: "q10", question: "52 + 36 = ?", answer: "88" },
      { id: "q11", question: "29 + 41 = ?", answer: "70" },
      { id: "q12", question: "63 + 17 = ?", answer: "80" },
      { id: "q13", question: "38 + 49 = ?", answer: "87" },
      { id: "q14", question: "55 + 25 = ?", answer: "80" },
      { id: "q15", question: "74 + 18 = ?", answer: "92" },
    ],
  },
  {
    id: "math-3",
    track: "math",
    number: 3,
    title: "Subtraction - Single Digit",
    description: "Subtract single-digit numbers. Type the answer.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "9 - 4 = ?", answer: "5" },
      { id: "q2", question: "8 - 3 = ?", answer: "5" },
      { id: "q3", question: "7 - 2 = ?", answer: "5" },
      { id: "q4", question: "6 - 1 = ?", answer: "5" },
      { id: "q5", question: "9 - 5 = ?", answer: "4" },
      { id: "q6", question: "8 - 6 = ?", answer: "2" },
      { id: "q7", question: "7 - 4 = ?", answer: "3" },
      { id: "q8", question: "9 - 7 = ?", answer: "2" },
      { id: "q9", question: "8 - 5 = ?", answer: "3" },
      { id: "q10", question: "6 - 4 = ?", answer: "2" },
      { id: "q11", question: "9 - 3 = ?", answer: "6" },
      { id: "q12", question: "5 - 2 = ?", answer: "3" },
      { id: "q13", question: "8 - 1 = ?", answer: "7" },
      { id: "q14", question: "9 - 9 = ?", answer: "0" },
      { id: "q15", question: "7 - 5 = ?", answer: "2" },
    ],
  },
  {
    id: "math-4",
    track: "math",
    number: 4,
    title: "Subtraction - Double Digit",
    description: "Subtract two-digit numbers. Type the difference.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "25 - 10 = ?", answer: "15" },
      { id: "q2", question: "37 - 14 = ?", answer: "23" },
      { id: "q3", question: "48 - 22 = ?", answer: "26" },
      { id: "q4", question: "55 - 30 = ?", answer: "25" },
      { id: "q5", question: "63 - 27 = ?", answer: "36" },
      { id: "q6", question: "72 - 38 = ?", answer: "34" },
      { id: "q7", question: "81 - 19 = ?", answer: "62" },
      { id: "q8", question: "90 - 45 = ?", answer: "45" },
      { id: "q9", question: "44 - 18 = ?", answer: "26" },
      { id: "q10", question: "67 - 29 = ?", answer: "38" },
      { id: "q11", question: "85 - 36 = ?", answer: "49" },
      { id: "q12", question: "52 - 17 = ?", answer: "35" },
      { id: "q13", question: "76 - 48 = ?", answer: "28" },
      { id: "q14", question: "93 - 56 = ?", answer: "37" },
      { id: "q15", question: "100 - 65 = ?", answer: "35" },
    ],
  },
  {
    id: "math-5",
    track: "math",
    number: 5,
    title: "Mixed Addition & Subtraction",
    description: "Mix it up! Type the answer to + and - problems.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "14 + 8 = ?", answer: "22" },
      { id: "q2", question: "20 - 7 = ?", answer: "13" },
      { id: "q3", question: "16 + 12 = ?", answer: "28" },
      { id: "q4", question: "30 - 14 = ?", answer: "16" },
      { id: "q5", question: "25 + 18 = ?", answer: "43" },
      { id: "q6", question: "40 - 22 = ?", answer: "18" },
      { id: "q7", question: "33 + 27 = ?", answer: "60" },
      { id: "q8", question: "55 - 19 = ?", answer: "36" },
      { id: "q9", question: "42 + 16 = ?", answer: "58" },
      { id: "q10", question: "60 - 35 = ?", answer: "25" },
      { id: "q11", question: "48 + 24 = ?", answer: "72" },
      { id: "q12", question: "75 - 28 = ?", answer: "47" },
      { id: "q13", question: "52 + 19 = ?", answer: "71" },
      { id: "q14", question: "84 - 47 = ?", answer: "37" },
      { id: "q15", question: "67 + 33 = ?", answer: "100" },
    ],
  },
  {
    id: "math-6",
    track: "math",
    number: 6,
    title: "Multiplication - 2, 5, 10",
    description: "Quick multiplication with easy times tables.",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "2 × 4 = ?", answer: "8" },
      { id: "q2", question: "5 × 3 = ?", answer: "15" },
      { id: "q3", question: "10 × 6 = ?", answer: "60" },
      { id: "q4", question: "2 × 7 = ?", answer: "14" },
      { id: "q5", question: "5 × 5 = ?", answer: "25" },
      { id: "q6", question: "10 × 4 = ?", answer: "40" },
      { id: "q7", question: "2 × 9 = ?", answer: "18" },
      { id: "q8", question: "5 × 8 = ?", answer: "40" },
      { id: "q9", question: "10 × 7 = ?", answer: "70" },
      { id: "q10", question: "2 × 6 = ?", answer: "12" },
      { id: "q11", question: "5 × 9 = ?", answer: "45" },
      { id: "q12", question: "10 × 9 = ?", answer: "90" },
      { id: "q13", question: "2 × 8 = ?", answer: "16" },
      { id: "q14", question: "5 × 7 = ?", answer: "35" },
      { id: "q15", question: "10 × 10 = ?", answer: "100" },
    ],
  },
  {
    id: "math-7",
    track: "math",
    number: 7,
    title: "Multiplication - 3, 4, 6",
    description: "Practice the 3, 4, and 6 times tables.",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "3 × 4 = ?", answer: "12" },
      { id: "q2", question: "4 × 5 = ?", answer: "20" },
      { id: "q3", question: "6 × 3 = ?", answer: "18" },
      { id: "q4", question: "3 × 7 = ?", answer: "21" },
      { id: "q5", question: "4 × 6 = ?", answer: "24" },
      { id: "q6", question: "6 × 5 = ?", answer: "30" },
      { id: "q7", question: "3 × 9 = ?", answer: "27" },
      { id: "q8", question: "4 × 8 = ?", answer: "32" },
      { id: "q9", question: "6 × 7 = ?", answer: "42" },
      { id: "q10", question: "3 × 6 = ?", answer: "18" },
      { id: "q11", question: "4 × 9 = ?", answer: "36" },
      { id: "q12", question: "6 × 9 = ?", answer: "54" },
      { id: "q13", question: "3 × 8 = ?", answer: "24" },
      { id: "q14", question: "4 × 7 = ?", answer: "28" },
      { id: "q15", question: "6 × 8 = ?", answer: "48" },
    ],
  },
  {
    id: "math-8",
    track: "math",
    number: 8,
    title: "Multiplication - 7, 8, 9",
    description: "The trickier times tables. Type fast!",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "7 × 3 = ?", answer: "21" },
      { id: "q2", question: "8 × 4 = ?", answer: "32" },
      { id: "q3", question: "9 × 5 = ?", answer: "45" },
      { id: "q4", question: "7 × 6 = ?", answer: "42" },
      { id: "q5", question: "8 × 7 = ?", answer: "56" },
      { id: "q6", question: "9 × 4 = ?", answer: "36" },
      { id: "q7", question: "7 × 7 = ?", answer: "49" },
      { id: "q8", question: "8 × 8 = ?", answer: "64" },
      { id: "q9", question: "9 × 6 = ?", answer: "54" },
      { id: "q10", question: "7 × 8 = ?", answer: "56" },
      { id: "q11", question: "8 × 9 = ?", answer: "72" },
      { id: "q12", question: "9 × 9 = ?", answer: "81" },
      { id: "q13", question: "7 × 9 = ?", answer: "63" },
      { id: "q14", question: "8 × 6 = ?", answer: "48" },
      { id: "q15", question: "9 × 7 = ?", answer: "63" },
    ],
  },
  {
    id: "math-9",
    track: "math",
    number: 9,
    title: "Division - Basics",
    description: "Split numbers evenly. Type the quotient.",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "10 ÷ 2 = ?", answer: "5" },
      { id: "q2", question: "12 ÷ 3 = ?", answer: "4" },
      { id: "q3", question: "20 ÷ 4 = ?", answer: "5" },
      { id: "q4", question: "15 ÷ 5 = ?", answer: "3" },
      { id: "q5", question: "18 ÷ 6 = ?", answer: "3" },
      { id: "q6", question: "21 ÷ 7 = ?", answer: "3" },
      { id: "q7", question: "24 ÷ 8 = ?", answer: "3" },
      { id: "q8", question: "27 ÷ 9 = ?", answer: "3" },
      { id: "q9", question: "30 ÷ 5 = ?", answer: "6" },
      { id: "q10", question: "36 ÷ 6 = ?", answer: "6" },
      { id: "q11", question: "42 ÷ 7 = ?", answer: "6" },
      { id: "q12", question: "48 ÷ 8 = ?", answer: "6" },
      { id: "q13", question: "54 ÷ 9 = ?", answer: "6" },
      { id: "q14", question: "63 ÷ 7 = ?", answer: "9" },
      { id: "q15", question: "72 ÷ 8 = ?", answer: "9" },
    ],
  },
  {
    id: "math-10",
    track: "math",
    number: 10,
    title: "Mixed - All Operations",
    description: "Final challenge! +, -, ×, ÷ all mixed together.",
    difficulty: "hard",
    questions: [
      { id: "q1", question: "12 + 14 = ?", answer: "26" },
      { id: "q2", question: "30 - 17 = ?", answer: "13" },
      { id: "q3", question: "6 × 7 = ?", answer: "42" },
      { id: "q4", question: "45 ÷ 9 = ?", answer: "5" },
      { id: "q5", question: "25 + 36 = ?", answer: "61" },
      { id: "q6", question: "50 - 24 = ?", answer: "26" },
      { id: "q7", question: "8 × 9 = ?", answer: "72" },
      { id: "q8", question: "56 ÷ 7 = ?", answer: "8" },
      { id: "q9", question: "47 + 28 = ?", answer: "75" },
      { id: "q10", question: "82 - 39 = ?", answer: "43" },
      { id: "q11", question: "9 × 6 = ?", answer: "54" },
      { id: "q12", question: "64 ÷ 8 = ?", answer: "8" },
      { id: "q13", question: "63 + 27 = ?", answer: "90" },
      { id: "q14", question: "100 - 47 = ?", answer: "53" },
      { id: "q15", question: "7 × 8 = ?", answer: "56" },
    ],
  },

  // ─── ECO GENIUS (Lessons 1-5) ───
  {
    id: "eco-1",
    track: "eco",
    number: 1,
    title: "Recycling Basics",
    description: "Learn quick facts about recycling and waste.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "Recycling 1 ton of paper saves 17 trees. T or F?", answer: "T" },
      { id: "q2", question: "Plastic takes about 500 years to decompose. T or F?", answer: "T" },
      { id: "q3", question: "Glass can be recycled forever. T or F?", answer: "T" },
      { id: "q4", question: "Aluminum cans take 200 years to break down. T or F?", answer: "T" },
      { id: "q5", question: "Most plastic in oceans comes from: a) cars b) bottles c) houses", answer: "b" },
      { id: "q6", question: "Rinse food off containers before recycling. T or F?", answer: "T" },
      { id: "q7", question: "A banana peel belongs in: a) recycling b) trash c) compost", answer: "c" },
      { id: "q8", question: "Paper towels are usually recyclable in curbside bins. T or F?", answer: "F" },
      { id: "q9", question: "The 'chasing arrows' symbol always means an item is recyclable everywhere. T or F?", answer: "F" },
      { id: "q10", question: "A reusable bottle is better than single-use plastic. T or F?", answer: "T" },
      { id: "q11", question: "Which is easiest to recycle: a) glass b) food c) diapers", answer: "a" },
      { id: "q12", question: "Composting helps reduce landfill methane. T or F?", answer: "T" },
      { id: "q13", question: "Trash in landfills breaks down quickly because there is lots of air. T or F?", answer: "F" },
      { id: "q14", question: "Old newspapers can be recycled into new paper. T or F?", answer: "T" },
      { id: "q15", question: "The 3 R's are Reduce, Reuse, Recycle. T or F?", answer: "T" },
    ],
  },
  {
    id: "eco-2",
    track: "eco",
    number: 2,
    title: "Animals & Habitats",
    description: "Match animals to the places they live and how they help nature.",
    difficulty: "easy",
    questions: [
      { id: "q1", question: "Pandas eat: a) fish b) bamboo c) meat", answer: "b" },
      { id: "q2", question: "Bees help plants by: a) making honey b) pollinating c) eating leaves", answer: "b" },
      { id: "q3", question: "Polar bears live in: a) Antarctica b) Arctic c) Africa", answer: "b" },
      { id: "q4", question: "Turtles can live over 100 years. T or F?", answer: "T" },
      { id: "q5", question: "A group of fish living in a coral reef is an example of a: a) habitat b) volcano c) factory", answer: "a" },
      { id: "q6", question: "Frogs often live near: a) water b) deserts c) outer space", answer: "a" },
      { id: "q7", question: "Wolves are: a) herbivores b) carnivores c) plants", answer: "b" },
      { id: "q8", question: "A camel is adapted to: a) rainforest b) desert c) ocean", answer: "b" },
      { id: "q9", question: "Penguins can fly long distances. T or F?", answer: "F" },
      { id: "q10", question: "Owls are most active at: a) night b) noon c) never", answer: "a" },
      { id: "q11", question: "Sea turtles breathe with: a) gills b) lungs c) roots", answer: "b" },
      { id: "q12", question: "A habitat provides food, water, shelter, and ___. (one word)", answer: "space" },
      { id: "q13", question: "Which animal is a pollinator: a) bee b) shark c) snake", answer: "a" },
      { id: "q14", question: "Deforestation can remove animal homes. T or F?", answer: "T" },
      { id: "q15", question: "A baby frog is called a: a) tadpole b) cub c) chick", answer: "a" },
    ],
  },
  {
    id: "eco-3",
    track: "eco",
    number: 3,
    title: "Trees & Forests",
    description: "Discover why forests matter and what trees do for us.",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "Trees produce: a) oxygen b) plastic c) sugar", answer: "a" },
      { id: "q2", question: "Trees absorb: a) oxygen b) carbon dioxide c) water", answer: "b" },
      { id: "q3", question: "Forests cover what % of Earth's land: a) 31% b) 50% c) 70%", answer: "a" },
      { id: "q4", question: "How long can a tree live? a) 50 years b) 1000 years c) 5000 years", answer: "c" },
      { id: "q5", question: "The layer of a forest made of leaves on the ground is called: a) litter b) metal c) lava", answer: "a" },
      { id: "q6", question: "Roots help a tree by: a) holding soil b) making TV c) throwing rocks", answer: "a" },
      { id: "q7", question: "Trees help stop soil from washing away. T or F?", answer: "T" },
      { id: "q8", question: "A rainforest gets: a) lots of rain b) no rain c) only snow", answer: "a" },
      { id: "q9", question: "Cutting down too many trees is called: a) deforestation b) decoration c) dehydration", answer: "a" },
      { id: "q10", question: "Leaves take in sunlight to make food. This process is called: a) photosynthesis b) teleporting c) freezing", answer: "a" },
      { id: "q11", question: "Forests are home to many species. T or F?", answer: "T" },
      { id: "q12", question: "Trees can help cool cities by providing: a) shade b) noise c) smoke", answer: "a" },
      { id: "q13", question: "A tree's trunk carries water and nutrients. T or F?", answer: "T" },
      { id: "q14", question: "Which is NOT a benefit of forests: a) clean air b) wildlife homes c) more plastic", answer: "c" },
      { id: "q15", question: "Planting trees can help fight climate change. T or F?", answer: "T" },
    ],
  },
  {
    id: "eco-4",
    track: "eco",
    number: 4,
    title: "Climate & Energy",
    description: "Learn the basics of energy choices and climate.",
    difficulty: "medium",
    questions: [
      { id: "q1", question: "The Sun is a source of clean energy. T or F?", answer: "T" },
      { id: "q2", question: "Wind is a renewable energy. T or F?", answer: "T" },
      { id: "q3", question: "Coal is a fossil fuel. T or F?", answer: "T" },
      { id: "q4", question: "Solar panels work at night. T or F?", answer: "F" },
      { id: "q5", question: "Electricity from moving air is called: a) wind power b) coal power c) lava power", answer: "a" },
      { id: "q6", question: "Burning fossil fuels releases: a) carbon dioxide b) oxygen c) ice", answer: "a" },
      { id: "q7", question: "Turning off unused devices saves energy. T or F?", answer: "T" },
      { id: "q8", question: "Energy from flowing water is: a) hydropower b) firepower c) sandpower", answer: "a" },
      { id: "q9", question: "A greenhouse gas traps heat in the atmosphere. T or F?", answer: "T" },
      { id: "q10", question: "The main gas humans add that warms the planet is: a) helium b) carbon dioxide c) neon", answer: "b" },
      { id: "q11", question: "Recycling uses less energy than making many items from raw materials. T or F?", answer: "T" },
      { id: "q12", question: "Which is renewable: a) oil b) sunlight c) natural gas", answer: "b" },
      { id: "q13", question: "LED bulbs use less energy than old bulbs. T or F?", answer: "T" },
      { id: "q14", question: "Planting trees can help by absorbing carbon dioxide. T or F?", answer: "T" },
      { id: "q15", question: "Leaving the fridge door open saves energy. T or F?", answer: "F" },
    ],
  },
  {
    id: "eco-5",
    track: "eco",
    number: 5,
    title: "Daily Eco Actions",
    description: "Everyday choices that help the planet.",
    difficulty: "hard",
    questions: [
      { id: "q1", question: "Turn off lights when leaving a room. Helps planet? T or F", answer: "T" },
      { id: "q2", question: "Best way to school: a) car alone b) walking c) flying", answer: "b" },
      { id: "q3", question: "Reusing a water bottle saves plastic. T or F?", answer: "T" },
      { id: "q4", question: "How many R's? Reduce, Reuse, ___", answer: "RECYCLE" },
      { id: "q5", question: "Take shorter showers to save: a) water b) pizza c) homework", answer: "a" },
      { id: "q6", question: "Bring your own bag to the store. T or F?", answer: "T" },
      { id: "q7", question: "Compost food scraps instead of trashing them. T or F?", answer: "T" },
      { id: "q8", question: "Best choice for a snack: a) local fruit b) extra plastic wrappers c) litter", answer: "a" },
      { id: "q9", question: "Picking up litter helps animals. T or F?", answer: "T" },
      { id: "q10", question: "Which saves energy: a) unplug chargers b) leave chargers in c) run TV all day", answer: "a" },
      { id: "q11", question: "Using both sides of paper reduces waste. T or F?", answer: "T" },
      { id: "q12", question: "Repairing items can reduce waste. T or F?", answer: "T" },
      { id: "q13", question: "Set thermostat a little lower in winter to save energy. T or F?", answer: "T" },
      { id: "q14", question: "The eco-friendly choice is to: a) waste food b) eat what you take c) throw food away", answer: "b" },
      { id: "q15", question: "Refillable pens reduce plastic waste. T or F?", answer: "T" },
    ],
  },
];
